import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case english = "English"
    case simplifiedChinese = "简体中文"

    var id: Self { self }
    var locale: Locale { Locale(identifier: self == .english ? "en_US" : "zh_Hans_CN") }
    var displayName: String { rawValue }
}

enum Localizer {
    // App-owned keys are centralized so localization coverage can be audited.
    static let simplifiedChinese: [String: String] = [
        "Campus Dashboard": "校园学习面板", "Today": "今日", "Schedule": "日程",
        "Tasks": "任务", "Announcements": "公告", "AI Confirmation Queue": "AI 确认队列",
        "Settings": "设置", "Refresh": "刷新", "Refreshing": "刷新中", "Open Settings": "打开设置",
        "Development preview": "开发预览", "All records are synthetic": "所有记录均为虚构数据",
        "Preview state": "预览状态", "Sample data": "示例数据", "Empty": "空状态",
        "Loading": "加载中", "Error": "错误", "Permission denied": "权限被拒绝",
        "Select a deterministic UI state": "选择确定性的界面状态",
        "Refresh synthetic preview data": "刷新虚构预览数据",
        "Synchronize sources and reload dashboard data": "同步来源并重新载入面板数据",
        "Refresh dashboard": "刷新面板", "Loading preview data": "正在加载预览数据",
        "The interface remains responsive while local data is prepared.": "准备本地数据时，界面仍可正常使用。",
        "Preview sync failed": "预览同步失败",
        "Synthetic source data could not be refreshed. Use Refresh to recover this demo state.": "无法刷新虚构来源数据。请点击“刷新”恢复此演示状态。",
        "This preview demonstrates a denied integration. Core local pages remain available; no system permission is requested in Stage 01.": "此预览展示集成权限被拒绝的状态。本地核心页面仍可使用；Stage 01 不会请求系统权限。",

        "Previous week": "上一周", "Next week": "下一周", "Current week": "本周",
        "Previous": "上一个", "Next": "下一个", "Return to today": "回到今天",
        "Day": "日", "Week": "周", "Month": "月", "Calendar view": "日历视图",
        "Weekly timetable": "每周课表", "Monday through Sunday": "星期一至星期日",
        "No classes this week": "本周没有课程", "No synchronized course meetings fall in this week.": "本周没有已同步的课程时段。",
        "Unread announcements": "未读公告", "No unread announcements": "没有未读公告",
        "New announcements will appear here until you mark them read.": "新公告会显示在这里，直到你将其标为已读。",
        "Mark read": "标为已读", "Mark unread": "标为未读", "Open source": "打开来源",
        "Published": "发布于", "Course": "课程", "Now": "现在",
        "Clipped at visible start": "早于可见时段", "Clipped at visible end": "晚于可见时段",
        "Compact sync status": "简要同步状态", "Background sync": "后台同步",
        "Last success": "最近成功", "Never synced": "从未同步", "Manual refresh": "手动刷新",
        "Refresh in progress": "正在刷新", "Ready": "就绪", "Needs attention": "需要处理", "Unavailable": "不可用",
        "Authorization needs attention.": "授权需要处理。", "The source denied this read.": "来源拒绝了此次读取。",
        "The last attempt was offline.": "上次尝试时网络离线。", "The source requested a retry delay.": "来源要求延迟后重试。",
        "The source contract needs attention.": "来源数据结构需要处理。", "The last synchronization needs attention.": "最近一次同步需要处理。",
        "There are no synchronized meetings, deadlines, announcements, or confirmations yet.": "尚无已同步的课程、截止事项、公告或待确认内容。",
        "Dashboard data is temporarily unavailable. Existing source data was not replaced.": "面板数据暂时不可用。现有来源数据未被替换。",
        "Source data unavailable": "来源数据不可用", "Try Refresh. If the problem continues, review source authorization in Settings.": "请尝试刷新。若问题持续，请在设置中检查来源授权。",

        "Course meetings and confirmed time-bound items": "课程时段与已确认的定时事项",
        "No scheduled items": "暂无日程", "No synchronized events match the current range and filters.": "当前范围和筛选条件下没有已同步的事项。",
        "All-day": "全天", "All-day items": "全天事项", "No all-day items": "没有全天事项",
        "Filters": "筛选", "All courses": "所有课程", "All sources": "所有来源", "All event types": "所有事项类型",
        "Course meeting": "课程时段", "Official deadline": "官方截止事项", "Confirmed inferred deadline": "已确认的推断截止事项",
        "Confirmed exam": "已确认的考试", "Confirmed schedule change": "已确认的日程变更", "Open change announcement": "打开变更公告",
        "Cancelled": "已取消", "Changed": "已变更", "Undated items": "无日期事项", "No undated items": "没有无日期事项",
        "Sync issue": "同步异常", "Event details": "事项详情", "Select an event": "选择一个事项",
        "Select an event to see its time, location, state, and original source.": "选择事项以查看时间、地点、状态和原始来源。",
        "Time": "时间", "Location": "地点", "State": "状态", "Source": "来源", "Active": "有效",
        "Open original source": "打开原始来源", "No source link": "无来源链接", "Current time": "当前时间",
        "Selected date": "所选日期", "Show day": "查看当日",

        "Official deadlines remain distinct from local suggestions": "官方截止时间与本地建议严格区分",
        "No tasks": "暂无任务", "No synchronized tasks match the current filter.": "没有符合当前筛选条件的已同步任务。",
        "Task type": "任务类型", "All types": "全部类型", "Official": "官方", "Suggested": "建议",
        "No official due date": "无官方截止时间", "Unknown course": "未知课程",
        "Assignment": "作业", "Quiz": "测验", "Reading": "阅读", "High": "高", "Medium": "中", "Low": "低",
        "Source content with local-only read state": "来源内容与仅保存在本地的已读状态",
        "No announcements": "暂无公告", "There are no synchronized announcements to show.": "没有可显示的已同步公告。",
        "Academic signal category": "学习信号分类", "All categories": "全部分类",
        "Course schedule change": "课程安排变更", "Assignment deadline": "作业截止安排",
        "Exam or Quiz time": "考试或测验时间", "Other": "其他",
        "AI labels are local suggestions, not Canvas facts.": "AI 标签是本地建议，并非 Canvas 官方事实。",
        "Deterministic analysis": "确定性分析", "DeepSeek analysis": "DeepSeek 分析",
        "Provider unavailable; deterministic result retained": "提供方不可用；已保留确定性结果",
        "AI disabled; deterministic result retained": "AI 已关闭；已保留确定性结果",
        "Not analyzed": "尚未分析", "Reprocess": "重新处理", "This issue is retryable.": "此问题可重试。",
        "Analyze this announcement again using the current local rules and enabled provider.": "使用当前本地规则和已启用的提供方重新分析此公告。",
        "No actionable academic signal was found.": "未发现可执行的学习信号。",
        "Evidence": "证据", "Key requirement": "关键要求", "Reason": "原因", "Conflicts": "冲突",
        "Correct academic signal": "修正学习信号", "Correct analysis…": "修正分析…", "Category": "分类",
        "Section needs review": "班别需要确认", "Time zone": "时区", "Reset": "重置",
        "A corrected date remains inferred and this save records explicit local confirmation.": "修正后的日期仍是推断日期；保存会记录明确的本地确认。",
        "The academic-signal decision could not be saved.": "无法保存学习信号决定。",
        "The academic-signal correction could not be saved.": "无法保存学习信号修正。",
        "deterministic_only": "仅确定性分析", "analyzed": "已分析",
        "not_required": "无需日期确认",
        "AI consent or configuration": "AI 同意或配置问题",
        "Review AI settings in Campus Dashboard.": "请检查 Campus Dashboard 的 AI 设置。",
        "API key unavailable in Keychain": "钥匙串中的 API 密钥不可用",
        "Review the API key in Campus Dashboard settings.": "请检查 Campus Dashboard 设置中的 API 密钥。",
        "Provider request configuration": "提供方请求配置问题",
        "Temporary connection or service issue": "临时连接或服务问题",
        "Retry later or review the app's DeepSeek route setting.": "请稍后重试，或检查应用的 DeepSeek 路由设置。",
        "Provider authorization rejected": "提供方拒绝授权",
        "Replace or verify the API key in Campus Dashboard settings.": "请在 Campus Dashboard 设置中更换或验证 API 密钥。",
        "Provider balance unavailable": "提供方余额不可用",
        "Review the provider account, then retry here.": "请检查提供方账户，然后在此重试。",
        "Provider rate limit": "提供方请求频率受限",
        "Wait, then reprocess this announcement.": "请稍候，然后重新处理此公告。",
        "Local AI budget reached": "已达到本地 AI 预算",
        "Review the local AI budget in Campus Dashboard settings.": "请检查 Campus Dashboard 设置中的本地 AI 预算。",
        "Provider response could not be safely used": "无法安全使用提供方响应",
        "Use the retained local result or reprocess later.": "请使用已保留的本地结果，或稍后重新处理。",
        "Analysis cancelled": "分析已取消", "Reprocess when ready.": "准备好后请重新处理。",
        "Provider unavailable": "提供方不可用",
        "Use the retained local result or review AI settings.": "请使用已保留的本地结果，或检查 AI 设置。",

        "Review suggestions before any inferred value can be used downstream": "在任何推断值用于后续功能前进行审核",
        "Nothing awaiting confirmation": "暂无待确认内容", "There are no inferred dates or organization suggestions in the queue.": "队列中没有推断日期或整理建议。",
        "Deterministic sync and all non-AI features remain available.": "确定性同步和所有非 AI 功能仍可使用。",
        "AI assistance is off": "AI 辅助已关闭", "Local deterministic AI fixture enabled": "本地确定性 AI 测试提供方已启用",
        "Official values always win. Dates extracted from text stay inferred until you confirm them; AI never calls Calendar or notifications.": "官方值始终优先。文本中提取的日期在你确认前仍为推断值；AI 永远不会调用日历或通知。",
        "Recent decisions": "最近决定", "Undo": "撤销", "Final adopted value": "最终采用值", "Organization": "整理建议",
        "Inferred date": "推断日期", "Conflict / uncertain": "冲突／不确定", "Original target": "原始对象",
        "Original context": "原始内容", "Normalized title": "规范化标题", "Suggested type": "建议类型",
        "Inferred date (not yet authorized)": "推断日期（尚未授权）", "Related-item suggestions only": "仅建议关联事项",
        "Action items": "行动项", "Confirm locally": "在本地确认", "Correct…": "修正…", "Reject": "拒绝", "Suggestion": "建议",
        "Preview only; persistent audit actions require the app database.": "仅供预览；持久化审计操作需要应用数据库。",
        "Correct suggestion": "修正建议", "Include inferred date": "包含推断日期", "Save correction": "保存修正", "Cancel": "取消",
        "A corrected date remains inferred. Saving is the explicit confirmation recorded in the audit trail.": "修正后的日期仍属于推断值。保存即是在审计记录中作出的明确确认。",

        "Calendar access is user-controlled and limited to one dedicated calendar": "日历访问由用户控制，并仅限一个专用日历",
        "Language": "语言", "Interface language": "界面语言", "Data sources": "数据源", "Sync": "同步",
        "Course reconciliation": "课程协调", "Mapping needs confirmation": "映射需要确认", "Mapped locally": "已在本地映射",
        "Kept separate locally": "已在本地保持分开", "Mapping decision undone": "映射决定已撤销",
        "Canvas and SIweb records stay unchanged. Confirmed mappings only provide one local dashboard identity.": "Canvas 与 SIweb 原始记录保持不变。已确认的映射只会在本地面板中提供一个统一课程身份。",
        "Map": "映射", "Keep separate": "保持分开",
        "Matched by full module code and title.": "已按完整课程代码与标题匹配。",
        "Matched by compatible module-code family and unique title.": "已按兼容的课程代码系列与唯一标题匹配。",
        "The title is uniquely shared, but the module-code families disagree. Review both sources before mapping.": "两个来源只有这一组标题相同，但课程代码系列不一致。映射前请核对双方来源。",
        "You confirmed this local mapping.": "你已确认此本地映射。", "You chose to keep these source records separate.": "你已选择让这些来源记录保持分开。",
        "This decision was reset for review.": "此决定已重置并等待复核。", "The most recent local decision was undone.": "最近一次本地决定已撤销。",
        "Local course reconciliation decision.": "本地课程协调决定。",
        "Release setup checklist": "发布准备清单", "Configured": "已配置", "Needs setup": "需要设置", "Optional": "可选",
        "Welcome to Campus Dashboard": "欢迎使用校园学习面板", "Open setup settings": "打开设置向导", "Continue for now": "暂时继续",
        "Dedicated Calendar": "专用日历", "Notifications": "通知", "Optional DeepSeek": "可选的 DeepSeek",
        "Canvas HTTPS address": "Canvas HTTPS 地址", "Canvas access token (saved only to Keychain)": "Canvas 访问令牌（仅存于钥匙串）",
        "Save or reauthorize Canvas": "保存或重新授权 Canvas", "Remove Canvas credential": "移除 Canvas 凭证",
        "Authorize or reauthorize SIweb in app": "在应用内授权或重新授权 SIweb", "Remove SIweb authorization": "移除 SIweb 授权",
        "Paused for school-policy review": "因学校政策审查而暂停", "Recovery center": "恢复中心", "Recover": "恢复",
        "Release outcome metrics": "发布结果指标", "Sync completed / failed": "同步成功／失败", "Average sync latency": "平均同步延迟",
        "Reviewed corrections": "已审核修正", "Critical misses corrected from Other": "从“其他”修正的关键漏项",
        "Provider failure / recovery": "提供方失败／恢复", "Duplicate / unsafe Calendar writes": "重复／不安全的日历写入",
        "Duplicate notification keys": "重复通知键", "Handling-time samples": "处理时长样本",
        "Other / no actionable result": "其他／无可执行结果", "Provider fallback": "提供方回退", "Calendar written": "已写入日历",
        "Ignore": "忽略", "Preview Calendar change…": "预览日历变更…", "Calendar change preview": "日历变更预览",
        "Operation": "操作", "Dedicated calendar": "专用日历", "Event type": "事项类型", "Accessible title marker": "无障碍标题标记",
        "Starts": "开始", "Ends": "结束", "Affected event": "受影响事项", "Undo effect": "撤销效果",
        "Confirm and allow Calendar reconciliation": "确认并允许日历协调", "Course cancellation": "课程取消",
        "Makeup / schedule change": "补课／日程变更", "Exam or Quiz": "考试或测验",
        "create": "创建", "update": "更新", "cancel": "取消", "ignored": "已忽略",
        "Connect only the services you want. Each row explains the minimum data used and can be changed later in Settings.": "只连接你需要的服务。每一项都会说明使用的最少数据，并可稍后在设置中更改。",
        "Configured securely.": "已安全配置。", "Add the Canvas HTTPS address and access token.": "添加 Canvas HTTPS 地址和访问令牌。",
        "Reads active courses, assignments, and announcements; the token stays in Keychain.": "仅读取当前课程、作业和公告；令牌始终保存在钥匙串中。",
        "Authorized session is in Keychain.": "授权会话已存入钥匙串。", "Sign in on MPU's non-persistent page.": "请在澳理大非持久化页面登录。",
        "Reads the approved timetable page; Campus Dashboard never reads login fields.": "仅读取获准的课表页面；校园学习面板绝不读取登录字段。",
        "Dedicated calendar verified.": "专用日历已验证。", "Grant access and select or create one dedicated calendar.": "授予权限并选择或创建一个专用日历。",
        "Writes only app-owned bound events in that calendar.": "仅在该日历中写入本应用拥有且已绑定的事项。",
        "Local notifications enabled.": "本地通知已启用。", "Enable notifications from a user action.": "请通过明确的用户操作启用通知。",
        "Schedules local reminders; no notification content is sent to a server.": "仅安排本地提醒；通知内容不会发送到服务器。",
        "Optional assistance enabled with current consent.": "已按当前同意启用可选辅助。", "Optional; deterministic results remain available.": "可选；确定性结果仍可使用。",
        "Sends only the bounded fields shown in the disclosure after explicit consent.": "明确同意后，仅发送披露中列出的有限字段。",
        "Canvas — exact HTTPS school host and a read-only access token": "Canvas — 学校的准确 HTTPS 主机和只读访问令牌",
        "SIweb — MPU read-only timetable session": "SIweb — 澳理大只读课表会话",
        "The sign-in page uses a non-persistent browser. Login fields are not inspected; only an eligible secure wapps2 session is kept in Keychain.": "登录页使用非持久化浏览器。应用不会检查登录字段；只会把符合条件的安全 wapps2 会话保存在钥匙串中。",
        "Outlook has no setup controls, background authorization, token lookup, mailbox probe, or network traffic in this release.": "此版本的 Outlook 没有设置控件、后台授权、令牌读取、邮箱探测或网络流量。",
        "Local aggregate operational measurements only. Synthetic QA runs must be reported separately and are not treated as real-user outcomes.": "仅显示本地汇总运行指标。合成质量检查必须单独报告，不视为真实用户结果。",
        "Authentication expired": "身份验证已过期", "Missing consent or Keychain item": "缺少同意或钥匙串项目",
        "Network or exact-host route": "网络或准确主机路由", "HTTP or rate limit": "HTTP 或速率限制", "Timeout": "超时",
        "Schema or decoding": "架构或解码", "Local AI budget": "本地 AI 预算", "Calendar permission": "日历权限", "Notification permission": "通知权限",
        "Cached data and other connected sources remain available.": "缓存数据及其他已连接来源仍可使用。",
        "Deterministic organization, source sync, and existing local history remain available.": "确定性整理、来源同步及现有本地历史仍可使用。",
        "Sync, review, and notifications remain available; no Calendar event is changed.": "同步、审核和通知仍可使用；不会更改任何日历事项。",
        "Sync, review, and Calendar remain available.": "同步、审核和日历仍可使用。",
        "Reconnect only the affected source in Settings, then refresh.": "仅在设置中重新连接受影响的来源，然后刷新。",
        "Review consent and the Keychain-backed credential in Settings.": "在设置中检查同意状态和钥匙串凭证。",
        "Restore the network or review the DeepSeek exact-host route, then retry.": "恢复网络或检查 DeepSeek 准确主机路由，然后重试。",
        "Wait for the requested delay, then retry only the affected subsystem.": "等待指定时间后，只重试受影响的子系统。",
        "Retry later; repeated attempts remain idempotent.": "稍后重试；重复操作仍保持幂等。",
        "Keep the retained local result and retry after the connector or provider is repaired.": "保留本地结果，在连接器或提供方修复后重试。",
        "Review the local request/token budget, then explicitly reprocess.": "检查本地请求／令牌预算，然后明确重新处理。",
        "Restore Calendar access in System Settings, then revalidate the dedicated calendar.": "在系统设置中恢复日历权限，然后重新验证专用日历。",
        "Restore Notifications in System Settings, then enable them here.": "在系统设置中恢复通知权限，然后在此启用。",
        "No actionable academic signal was found. You can correct this result locally or ignore it.": "未找到可执行的学业信号。你可以在本地修正或忽略此结果。",
        "No existing bound event": "没有现有绑定事项", "Existing app-owned bound event": "现有的应用自有绑定事项",
        "Undo removes the app-owned event created from this confirmation.": "撤销会移除此确认所创建的应用自有事项。",
        "Undo restores the prior app-owned bound event on reconciliation.": "撤销后，协调过程会恢复先前的应用自有绑定事项。",
        "This preview has not changed Calendar. Confirming records the local decision and idempotently reconciles only the app-owned bound event.": "此预览尚未更改日历。确认会记录本地决定，并以幂等方式仅协调应用自有的绑定事项。",
        "Authorize MPU SIWeb (read-only)": "授权澳理大 SIWeb（只读）", "MPU SIWeb sign-in page": "澳理大 SIWeb 登录页面",
        "Sign in directly on MPU's non-persistent page. Campus Dashboard does not read the login form. After MPU returns to SIWeb, only the authorized wapps2 session is stored in Keychain.": "请直接在澳理大的非持久化页面登录。校园学习面板不会读取登录表单。返回 SIWeb 后，只会把已授权的 wapps2 会话存入钥匙串。",
        "Closing this window cancels authorization and does not affect Canvas, Calendar, or notifications.": "关闭此窗口会取消授权，不会影响 Canvas、日历或通知。",
        "Automatic sync (60-minute target)": "自动同步（目标间隔 60 分钟）",
        "This is a target interval only. The app cannot run while the Mac is asleep, off, or no user is logged in.": "这只是目标间隔。Mac 休眠、关机或没有用户登录时，应用无法运行。",
        "Open macOS Login Items settings": "打开 macOS 登录项设置", "System integrations": "系统集成", "Apple Calendar": "Apple 日历",
        "Local notifications": "本地通知", "Enable / Refresh": "启用／刷新", "Notification master switch": "通知总开关",
        "Deadline lead minutes": "截止提醒提前分钟数", "Apply": "应用",
        "Comma-separated minutes before a deadline; defaults are 1440, 180, and 60.": "用逗号分隔截止前分钟数；默认值为 1440、180 和 60。",
        "Class reminder lead": "上课提醒提前量", "minutes": "分钟", "Quiet starts": "静默开始", "Quiet ends": "静默结束",
        "Notifications in quiet hours move to quiet-end only when still useful; otherwise they are discarded.": "静默时段内的通知仅在仍有意义时延后至静默结束，否则将被丢弃。",
        "Course notifications": "课程通知", "Schedule synthetic test notification": "安排虚构测试通知",
        "Calendar source": "日历来源", "Create dedicated Campus Dashboard calendar": "创建 Campus Dashboard 专用日历",
        "Existing dedicated calendar": "现有专用日历", "Select a calendar": "选择日历", "Use selected dedicated calendar": "使用所选专用日历",
        "Select only a calendar dedicated to Campus Dashboard. Names are never used as identity.": "只能选择 Campus Dashboard 专用日历。名称永远不会用作身份标识。",
        "AI assistance": "AI 辅助", "AI-assisted organization": "AI 辅助整理",
        "Provider: deterministic local fixture · no network access": "提供方：确定性本地测试实现 · 无网络访问",
        "External providers remain unavailable until provider, transmitted fields, retention policy, and explicit consent are recorded.": "在记录提供方、传输字段、保留政策及明确同意前，外部提供方保持不可用。",
        "DeepSeek enabled": "DeepSeek 已启用", "DeepSeek disabled": "DeepSeek 已关闭",
        "Disable and revoke consent": "关闭并撤销同意", "Review and enable DeepSeek…": "查看说明并启用 DeepSeek…",
        "Current provider and model": "当前提供方与模型",
        "DeepSeek API key (saved only to Keychain)": "DeepSeek API 密钥（仅存入钥匙串）",
        "Save key": "保存密钥", "Remove key": "移除密钥",
        "API key is stored in Keychain.": "API 密钥已存入钥匙串。", "No DeepSeek API key is stored.": "钥匙串中没有 DeepSeek API 密钥。",
        "Connect directly only for DeepSeek API": "仅 DeepSeek API 直连",
        "Off by default. When enabled, only HTTPS requests to api.deepseek.com bypass the macOS system proxy. This does not change FlClash, VPN, or global network settings. Other hosts and apps continue using their normal settings.": "默认关闭。启用后，仅发往 api.deepseek.com 的 HTTPS 请求绕过 macOS 系统代理。此选项不会更改 FlClash、VPN 或全局网络设置；其他主机和应用仍使用其正常设置。",
        "Request and token budgets": "请求与 Token 预算", "Per run requests": "每次运行请求数",
        "Daily requests": "每日请求数", "Per run tokens": "每次运行 Token 数", "Daily tokens": "每日 Token 数",
        "Apply budgets": "应用预算", "Clear local AI results…": "清除本地 AI 结果…",
        "Today's aggregate usage": "今日汇总用量", "requests": "次请求", "input tokens": "输入 Token",
        "output tokens": "输出 Token", "estimated maximum-rate cost": "按最高费率估算成本",
        "Enable external AI processing": "启用外部 AI 处理",
        "Selected text leaves this Mac and is processed or stored in the People's Republic of China or outside your region.": "所选文本将离开此 Mac，并可能在中华人民共和国境内或你所在地区以外处理或存储。",
        "Fields this feature may transmit": "此功能可能传输的字段",
        "Selected Canvas title; bounded visible text excerpt; minimum course name and course code; local section constraint; up to 24 mapped SIweb meeting candidate IDs, start/end times, and time zones; official item type and official due date when present; interface locale; fixed JSON schema instructions. No meeting location, Canvas URL, account or student identifier, author email, recipients, attachments, cookies, tokens, hidden HTML, remote content, correction history, or unrelated history.": "所选 Canvas 标题；有长度限制的可见文本摘录；最少课程名称与课程代码；本地班别约束；最多 24 个已映射 SIweb 上课候选项的标识、开始与结束时间及其时区；如有则包含官方事项类型与官方截止日期；界面区域设置；固定 JSON 架构指令。不包含上课地点、Canvas URL、账号或学生标识、作者邮箱、收件人、附件、Cookie、令牌、隐藏 HTML、远程内容、更正历史或无关历史。",
        "Selected Canvas title; bounded visible text excerpt; minimum course name; official item type and official due date when present; interface locale; fixed JSON schema instructions. No Canvas URL, account or student identifier, author email, recipients, attachments, cookies, tokens, hidden HTML, remote content, or unrelated history.": "所选 Canvas 标题；有长度限制的可见文本摘录；最少课程名称；如有则包含官方事项类型与官方截止日期；界面区域设置；固定 JSON 架构指令。不包含 Canvas URL、账号或学生标识、作者邮箱、收件人、附件、Cookie、令牌、隐藏 HTML、远程内容或无关历史。",
        "Retention warning: no fixed API-input deletion period is disclosed. Inputs may be retained for service, legal, security, and improvement purposes.": "保留警告：提供方未披露固定的 API 输入删除期限。输入可能因服务、法律、安全及改进目的而被保留。",
        "Privacy policy": "隐私政策", "Open Platform terms": "开放平台服务条款",
        "I confirmed that my school policy permits sending these selected fields to this external provider.": "我已确认学校政策允许将这些所选字段发送给此外部提供方。",
        "If school policy forbids external processing, do not enable DeepSeek.": "如果学校政策禁止外部处理，请勿启用 DeepSeek。",
        "Consent and enable": "同意并启用",
        "DeepSeek is enabled with current consent. Only approved bounded fields may leave this Mac.": "DeepSeek 已在当前同意下启用。只有获准且有长度限制的字段可能离开此 Mac。",
        "DeepSeek API key saved in Keychain. It is never displayed again.": "DeepSeek API 密钥已存入钥匙串，之后不会再次显示。",
        "The DeepSeek API key could not be saved. No key was retained in ordinary settings.": "无法保存 DeepSeek API 密钥。普通设置中未保留密钥。",
        "DeepSeek was disabled, consent revoked, and its API key removed from Keychain.": "DeepSeek 已关闭、同意已撤销，API 密钥已从钥匙串移除。",
        "The DeepSeek key could not be removed. DeepSeek remains disabled.": "无法移除 DeepSeek 密钥。DeepSeek 保持关闭。",
        "DeepSeek was not enabled. Save a Keychain API key and confirm the school-policy warning first.": "DeepSeek 未启用。请先将 API 密钥存入钥匙串并确认学校政策警告。",
        "Consent could not be updated. DeepSeek remains unavailable.": "无法更新同意状态。DeepSeek 保持不可用。",
        "DeepSeek request and token budgets were updated.": "DeepSeek 请求与 Token 预算已更新。",
        "DeepSeek budgets were invalid and were not changed.": "DeepSeek 预算无效，未作更改。",
        "Direct HTTPS is enabled only for api.deepseek.com. FlClash and global network settings were not changed.": "仅 api.deepseek.com 的 HTTPS 直连已启用。FlClash 和全局网络设置均未更改。",
        "DeepSeek uses the macOS system proxy. FlClash and global network settings were not changed.": "DeepSeek 使用 macOS 系统代理。FlClash 和全局网络设置均未更改。",
        "The DeepSeek network route could not be updated. No system network setting was changed.": "无法更新 DeepSeek 网络路由。未更改任何系统网络设置。",
        "Privacy": "隐私", "Calendar writes are restricted to the verified dedicated calendar and bound events": "日历写入仅限已验证的专用日历和已绑定事项",
        "Clear local data by category": "按类别清除本地数据", "Clear…": "清除…", "Credentials in Keychain": "钥匙串中的凭证",
        "This is separate from cached-data clearing and does not remove Calendar events.": "此操作与清除缓存数据相互独立，且不会移除日历事项。",
        "Clear credentials…": "清除凭证…", "Preview Apple Calendar cleanup": "预览 Apple 日历清理", "Delete previewed events…": "删除已预览事项…",
        "Calendar cleanup is never part of ordinary local-data clearing. Only bindings revalidated in the dedicated calendar appear here.": "日历清理绝不属于普通本地数据清除。这里只有在专用日历中重新验证的绑定。",
        "Redacted diagnostics": "脱敏诊断", "The export is allowlisted: status categories, recovery actions, schema version, and aggregate counts only.": "导出采用允许列表：仅含状态类别、恢复操作、架构版本和汇总数量。",
        "Refresh diagnostics": "刷新诊断", "Export redacted diagnostics…": "导出脱敏诊断…", "View redacted diagnostic report": "查看脱敏诊断报告",
        "Confirm separate destructive operation": "确认独立的破坏性操作", "Clear credentials from Keychain": "从钥匙串清除凭证",
        "Delete only previewed app-owned events": "仅删除已预览且由应用拥有的事项",
        "Removes Canvas and SIweb credentials from Keychain only. Cached data and Calendar events remain.": "仅从钥匙串移除 Canvas 和 SIweb 凭证。缓存数据和日历事项会保留。",
        "Deletes only events shown in the preview after their app ownership is revalidated.": "仅删除预览中显示且已重新验证为应用拥有的事项。",
        "No integrations configured": "未配置集成", "Stage 01 intentionally has no source accounts, permissions, or external services.": "Stage 01 特意不包含来源账号、权限或外部服务。",
        "Source cache": "来源缓存", "Local user state": "本地用户状态", "Sync history": "同步历史", "AI history": "AI 历史",
        "Completed notification history": "已完成通知历史", "Local completion and read state": "本地完成与已读状态",
        "AI suggestions and history": "AI 建议与历史", "Notification delivery history": "通知投递历史",
        "Removes locally cached source records. Credentials and Apple Calendar events are retained.": "移除本地缓存的来源记录。凭证和 Apple 日历事项会保留。",
        "Removes local completion, read, hidden, and priority state only.": "仅移除本地完成、已读、隐藏和优先级状态。",
        "Removes completed synchronization and change history only.": "仅移除已完成的同步与变更历史。",
        "Removes AI parse results, decisions, and audit history only.": "仅移除 AI 解析结果、决定和审计历史。",
        "Removes completed notification delivery records only; scheduled reminders remain managed.": "仅移除已完成的通知投递记录；已安排提醒仍会继续管理。",
        "Clear": "清除", "App-owned event eligible for cleanup": "可清理的应用自有事项",
        "ready": "就绪", "not_configured": "未配置", "authorization_required": "需要授权",
        "permission_denied": "权限被拒绝", "offline": "离线", "rate_limited": "频率受限",
        "source_changed": "来源已变化", "service_unavailable": "服务不可用", "cancelled": "已取消", "failed": "失败",
        "pending": "待确认", "confirmed": "已确认", "corrected": "已修正", "rejected": "已拒绝", "undone": "已撤销",
        "iCloud": "iCloud", "local": "本机", "exchange": "Exchange", "calDAV": "CalDAV", "other": "其他",
        "Clear filters": "清除筛选",
        "Calendar sync is not configured.": "尚未配置日历同步。", "Notifications are not enabled.": "通知尚未启用。",
        "Background sync is disabled.": "后台同步已关闭。", "AI assistance is off. Deterministic organization remains available.": "AI 辅助已关闭。确定性整理功能仍可使用。",
        "Diagnostics have not been refreshed.": "诊断尚未刷新。", "Local data, credentials, and Calendar cleanup are separate operations.": "本地数据、凭证和日历清理是相互独立的操作。",
        "AI persistence is unavailable; deterministic screens remain usable.": "AI 持久化不可用；确定性界面仍可使用。",
        "Deterministic fake provider enabled. No content leaves this Mac.": "已启用确定性测试提供方。任何内容都不会离开此 Mac。",
        "AI settings could not be loaded. Deterministic synchronization remains available.": "无法载入 AI 设置。确定性同步仍可使用。",
        "AI settings could not be saved. No source or Calendar data was changed.": "无法保存 AI 设置。来源数据和日历均未更改。",
        "The AI decision could not be saved. No downstream action was taken.": "无法保存 AI 决定。未执行任何后续操作。",
        "The AI correction could not be saved. No downstream action was taken.": "无法保存 AI 修正。未执行任何后续操作。",
        "The AI decision could not be undone. Existing confirmed state was preserved.": "无法撤销 AI 决定。现有确认状态已保留。",
        "The AI decision was saved, but deadline notifications could not be updated. They will be reconciled on the next refresh.": "AI 决定已保存，但无法更新截止通知。下次刷新时会重新协调。",
        "Notification persistence is unavailable.": "通知持久化不可用。", "Permission has not been requested. Use Enable to ask from this screen.": "尚未请求权限。请在此界面使用“启用”进行请求。",
        "Notification permission is denied or was revoked. Sync and other views remain available.": "通知权限被拒绝或已撤销。同步和其他界面仍可使用。",
        "Local notifications are enabled.": "本地通知已启用。", "Permission is available, but the notification master switch is off.": "已有通知权限，但通知总开关已关闭。",
        "Notification settings could not be loaded. Other features remain available.": "无法载入通知设置。其他功能仍可使用。",
        "Notification permission or settings could not be updated. Other features remain available.": "无法更新通知权限或设置。其他功能仍可使用。",
        "Notification settings could not be updated. Existing settings were preserved.": "无法更新通知设置。现有设置已保留。",
        "Notification timing could not be updated. Existing settings were preserved.": "无法更新通知时间。现有设置已保留。",
        "Course notification settings could not be updated.": "无法更新课程通知设置。", "The test notification could not be scheduled.": "无法安排测试通知。",
        "A synthetic test notification is scheduled for about five seconds from now.": "已安排约五秒后发送虚构测试通知。",
        "Background scheduling is unavailable.": "后台调度不可用。", "Background settings could not be loaded. Foreground refresh remains available.": "无法载入后台设置。前台刷新仍可使用。",
        "Background item could not be changed. Foreground refresh remains available.": "无法更改后台项目。前台刷新仍可使用。",
        "Enabled with a 60-minute target while you are logged in and the Mac can run. Missed intervals are recovered after launch, wake, or network return.": "用户已登录且 Mac 可运行时，以 60 分钟为目标间隔启用。启动、唤醒或网络恢复后会补偿错过的间隔。",
        "Enabled in the app, but macOS requires approval in Login Items.": "应用内已启用，但 macOS 要求在登录项中批准。",
        "The app setting is on, but the macOS Login Item is off. Enable it in System Settings or toggle this setting again.": "应用设置已开启，但 macOS 登录项已关闭。请在系统设置中启用，或再次切换此设置。",
        "The macOS background item status is unavailable; foreground use still works.": "macOS 后台项目状态不可用；前台使用仍可正常工作。",
        "Calendar persistence is unavailable.": "日历持久化不可用。", "Calendar permission was denied. Other app features remain available.": "日历权限被拒绝。应用其他功能仍可使用。",
        "Full Calendar access is required to configure app-owned events.": "配置应用自有事项需要完整日历访问权限。",
        "Calendar permission was revoked. Existing bindings are preserved and no event will be touched.": "日历权限已撤销。现有绑定会保留，且不会更改任何事项。",
        "Choose a writable source to create, or explicitly select, a dedicated calendar.": "请选择可写来源以创建专用日历，或明确选择一个专用日历。",
        "Calendar access could not be updated. No event was changed.": "无法更新日历访问。未更改任何事项。",
        "The dedicated calendar could not be created. No unrelated calendar was changed.": "无法创建专用日历。未更改任何无关日历。",
        "The dedicated calendar could not be selected. No event was changed.": "无法选择专用日历。未更改任何事项。",
        "The dedicated calendar needs attention. Revalidate it in Settings.": "专用日历需要处理。请在设置中重新验证。",
        "Dedicated calendar verified in iCloud; iPhone arrival timing is controlled by iCloud.": "已在 iCloud 中验证专用日历；到达 iPhone 的时间由 iCloud 控制。",
        "Dedicated calendar verified; this source is not iCloud and is available only on this Mac/account source.": "专用日历已验证；该来源不是 iCloud，仅适用于此 Mac／账号来源。",
        "Not configured.": "未配置。", "Configure this source before synchronizing.": "请先配置此来源再同步。",
        "Diagnostic persistence is unavailable. Other local screens remain usable.": "诊断持久化不可用。其他本地界面仍可使用。",
        "Local state could not be saved. Source data was not changed.": "无法保存本地状态。来源数据未更改。",
        "Local state could not be loaded. Source data was not changed.": "无法载入本地状态。来源数据未更改。",
        "No action needed.": "无需操作。", "Reconnect this source using the secure authorization flow.": "请使用安全授权流程重新连接此来源。",
        "The source denied access.": "来源拒绝访问。", "Check account access or reconnect the source.": "请检查账号访问权限或重新连接来源。",
        "The Mac was offline during the last attempt.": "上次尝试时 Mac 处于离线状态。", "Reconnect to the network; recovery sync will retry.": "请重新连接网络；恢复同步会再次尝试。",
        "The source asked the app to slow down.": "来源要求应用降低请求频率。", "Wait for the automatic retry or refresh later.": "请等待自动重试，或稍后刷新。",
        "The source response no longer matches its safe contract.": "来源响应不再符合安全数据契约。", "Update or repair the connector before retrying.": "重试前请更新或修复连接器。",
        "The source service was temporarily unavailable.": "来源服务暂时不可用。", "Try again later; other sources remain available.": "请稍后再试；其他来源仍可使用。",
        "The last synchronization was cancelled.": "最近一次同步已取消。", "Refresh again when ready.": "准备好后请再次刷新。",
        "The last synchronization failed.": "最近一次同步失败。", "Review this source configuration and retry.": "请检查此来源的配置并重试。",
        "Enable or restore Calendar access in Settings.": "请在设置中启用或恢复日历访问。", "Enable or restore Notifications in Settings.": "请在设置中启用或恢复通知。",
        "AI is optional; deterministic synchronization remains available.": "AI 为可选功能；确定性同步仍可使用。",
        "Foreground refresh remains available; review Login Items if desired.": "前台刷新仍可使用；如有需要，请检查登录项。",
        "That local data category could not be cleared. No credential or Calendar cleanup was attempted.": "无法清除该本地数据类别。未尝试清除凭证或日历。",
        "Canvas and SIweb credentials were cleared from Keychain. Cached local data and Apple Calendar events were retained.": "已从钥匙串清除 Canvas 和 SIweb 凭证。缓存的本地数据和 Apple 日历事项已保留。",
        "Canvas, SIweb, and School Outlook credentials were cleared from Keychain. Cached local data and Apple Calendar events were retained.": "已从钥匙串清除 Canvas、SIweb 和学校 Outlook 凭证。缓存的本地数据和 Apple 日历事项已保留。",
        "Removes Canvas, SIweb, and School Outlook credentials from Keychain only. Cached data and Calendar events remain.": "仅从钥匙串移除 Canvas、SIweb 和学校 Outlook 凭证。缓存数据和日历事项会保留。",
        "Calendar cleanup is unavailable; no local data was changed.": "日历清理不可用；未更改本地数据。",
        "No verified app-owned Calendar events are eligible for cleanup.": "没有可清理的已验证应用自有日历事项。",
        "Review the verified app-owned events below before deleting them.": "删除前请检查下方已验证的应用自有事项。",
        "Calendar cleanup preview requires full access and a valid dedicated calendar. No event was changed.": "预览日历清理需要完整访问权限和有效的专用日历。未更改任何事项。",
        "Calendar cleanup stopped because ownership could not be revalidated. Unrelated events were not touched.": "由于无法重新验证所有权，日历清理已停止。未触碰无关事项。",
        "Redacted diagnostics exported. The report contains categories and aggregate counts only.": "脱敏诊断已导出。报告仅包含类别和汇总数量。",
        "prompt": "提示词版本", "schema": "架构版本", "Type suggestion": "类型建议", "Related item": "关联事项", "Action item": "行动项",
        "Clear operation completed. Credentials and Apple Calendar events were not changed.": "清除操作已完成。凭证和 Apple 日历事项均未更改。",
        "Verified app-owned Calendar events were removed from the dedicated calendar.": "已从专用日历移除经验证的应用自有事项。",
        "One or more Keychain items could not be cleared. Try again after unlocking Keychain.": "无法清除一个或多个钥匙串项目。请解锁钥匙串后重试。",
        "The redacted diagnostic report could not be exported.": "无法导出脱敏诊断报告。",
        "Choose a local file location for the diagnostic export.": "请为诊断导出选择本地文件位置。",
        "not_determined": "尚未决定", "denied": "已拒绝", "restricted": "受限制", "full_access": "完整访问",
        "write_only": "仅写入", "authorized": "已授权", "enabled": "已启用", "disabled": "已关闭",
        "enabled_local": "已启用（本地）", "requires_approval": "需要批准", "unavailable": "不可用", "healthy": "正常",
        "valid": "有效", "missing": "缺失", "ambiguous": "不明确", "unwritable": "不可写",
        "app_created": "应用创建", "user_selected": "用户选择",
        "School Outlook": "学校 Outlook 邮箱", "Delegated read-only authorization": "委托式只读授权",
        "School Outlook is not configured.": "尚未配置学校 Outlook。", "School Outlook is disconnected.": "学校 Outlook 已断开连接。",
        "School Outlook authorization is unavailable. Canvas and SIweb remain available.": "学校 Outlook 授权不可用。Canvas 和 SIweb 仍可正常使用。",
        "Continue authorization in the system browser.": "请在系统浏览器中继续授权。",
        "Connected with delegated Mail.ReadBasic. Mail content is not synchronized in this stage.": "已使用委托式 Mail.ReadBasic 连接。本阶段不会同步邮件内容。",
        "School Outlook authorization expired or was revoked. Reconnect interactively.": "学校 Outlook 授权已过期或撤销。请重新进行交互式连接。",
        "The school tenant requires administrator approval. Outlook remains off.": "学校租户需要管理员批准。Outlook 保持关闭。",
        "The school tenant policy blocked this app. Outlook remains off.": "学校租户策略阻止了此应用。Outlook 保持关闭。",
        "Microsoft application (client) ID": "Microsoft 应用程序（客户端）ID", "School directory (tenant) ID": "学校目录（租户）ID",
        "Use the values from your local public-client app registration. No client secret is accepted. The registered redirect URI must be msauth.com.campusdashboard.desktop://auth.": "请使用本地公共客户端应用注册中的值。本应用不接受客户端密码。注册的重定向 URI 必须为 msauth.com.campusdashboard.desktop://auth。",
        "Configure and connect in system browser": "配置并在系统浏览器中连接", "Run metadata-only check": "运行仅元数据检查",
        "Disconnect and clear tokens": "断开连接并清除令牌",
        "Requested delegated scopes: Mail.ReadBasic, openid, offline_access. This stage does not synchronize mail, read bodies or attachments, use shared mailboxes, or change the mailbox.": "请求的委托式范围：Mail.ReadBasic、openid、offline_access。本阶段不会同步邮件、读取正文或附件、使用共享邮箱，也不会更改邮箱。",
        "Connect only if your school policy permits this local public-client application. Administrator approval and Conditional Access are hard gates.": "仅在学校政策允许此本地公共客户端应用时连接。管理员批准和条件访问均为不可绕过的门槛。",
        "Outlook configuration or authorization could not start. Check the registered client and tenant values.": "无法启动 Outlook 配置或授权。请检查已注册的客户端和租户值。",
        "School Outlook tokens were removed from Keychain. No mailbox content was changed.": "已从钥匙串移除学校 Outlook 令牌。未更改任何邮箱内容。",
        "School Outlook could not be disconnected because Keychain was unavailable.": "由于钥匙串不可用，无法断开学校 Outlook。",
        "Connected. The minimum metadata-only check succeeded with no recent item returned.": "已连接。最小化的仅元数据检查成功，未返回近期项目。",
        "Connected. The minimum metadata-only check succeeded.": "已连接。最小化的仅元数据检查成功。",
        "Microsoft requires another interactive sign-in for MFA or Conditional Access.": "Microsoft 要求再次进行交互式登录，以满足 MFA 或条件访问要求。",
        "The metadata-only check failed safely. Canvas and SIweb remain available.": "仅元数据检查已安全失败。Canvas 和 SIweb 仍可正常使用。",
        "disconnected": "未连接", "authorizing": "授权中", "connected": "已连接", "expired": "已过期",
        "adminApprovalRequired": "需要管理员批准", "policyBlocked": "策略已阻止"
    ]

    static func text(_ english: String, language: AppLanguage) -> String {
        language == .simplifiedChinese ? (simplifiedChinese[english] ?? english) : english
    }

    static func format(_ date: Date, date dateStyle: Date.FormatStyle.DateStyle = .abbreviated,
                       time timeStyle: Date.FormatStyle.TimeStyle = .shortened,
                       language: AppLanguage, timeZone: TimeZone) -> String {
        let formatter = DateFormatter()
        formatter.locale = language.locale; formatter.timeZone = timeZone
        formatter.dateStyle = dateFormatterStyle(dateStyle); formatter.timeStyle = timeFormatterStyle(timeStyle)
        return formatter.string(from: date)
    }

    static func weekday(_ date: Date, width: Date.FormatStyle.Symbol.Weekday = .wide,
                        language: AppLanguage, timeZone: TimeZone) -> String {
        let formatter = DateFormatter()
        formatter.locale = language.locale; formatter.timeZone = timeZone
        formatter.dateFormat = width == .wide ? "EEEE" : "EEE"
        return formatter.string(from: date)
    }

    static func monthYear(_ date: Date, language: AppLanguage, timeZone: TimeZone) -> String {
        let formatter = DateFormatter()
        formatter.locale = language.locale; formatter.timeZone = timeZone; formatter.setLocalizedDateFormatFromTemplate("LLLL y")
        return formatter.string(from: date)
    }

    static func relative(_ date: Date, relativeTo now: Date, language: AppLanguage) -> String {
        let formatter = RelativeDateTimeFormatter()
        formatter.locale = language.locale
        formatter.unitsStyle = .full
        return formatter.localizedString(for: date, relativeTo: now)
    }

    private static func dateFormatterStyle(_ style: Date.FormatStyle.DateStyle) -> DateFormatter.Style {
        switch style { case .omitted: .none; case .numeric: .short; case .abbreviated: .medium; case .long: .long; case .complete: .full; default: .medium }
    }

    private static func timeFormatterStyle(_ style: Date.FormatStyle.TimeStyle) -> DateFormatter.Style {
        switch style { case .omitted: .none; case .shortened: .short; case .standard: .medium; case .complete: .long; default: .short }
    }
}
